# logistic Regression with sklearn

In [75]:
import pandas as pd

In [76]:
df = pd.read_csv('./data/uva.txt', sep='\t')
df.head()

who  Newbie   Age  Gender Household Income Sexual Preference  \
0  id74364       0  54.0    Male           $50-74          Gay male   
1  id84505       0  39.0  Female        Over $100      Heterosexual   
2  id84509       1  49.0  Female           $40-49      Heterosexual   
3  id87028       1  22.0  Female           $40-49      Heterosexual   
4  id76087       0  20.0    Male           $30-39          Bisexual   

      Country Education Attainment Major Occupation Marital Status  \
0     Ontario         Some College         Computer          Other   
1      Sweden         Professional            Other          Other   
2  Washington         Some College       Management          Other   
3     Florida         Some College         Computer        Married   
4  New Jersey         Some College        Education         Single   

  Years on Internet  
0            4-6 yr  
1            1-3 yr  
2        Under 6 mo  
3           6-12 mo  
4            1-3 yr

In [77]:
df.pop('who')
df.pop('Country')
df.pop('Years on Internet')

df.dtypes

Newbie                    int64
Age                     float64
Gender                   object
Household Income         object
Sexual Preference        object
Education Attainment     object
Major Occupation         object
Marital Status           object
dtype: object

In [78]:
df["Gender"] = df["Gender"].astype("category")
df["Household Income"] = df["Household Income"].astype("category")
df["Sexual Preference"] = df["Sexual Preference"].astype("category")
df["Education Attainment"] = df["Education Attainment"].astype("category")
df["Major Occupation"] = df["Major Occupation"].astype("category")
df["Marital Status"] = df["Marital Status"].astype("category")

df.dtypes

Newbie                     int64
Age                      float64
Gender                  category
Household Income        category
Sexual Preference       category
Education Attainment    category
Major Occupation        category
Marital Status          category
dtype: object

In [79]:
df = pd.get_dummies(df)
df.shape

(19583, 38)

In [80]:
df.loc[pd.isnull(df['Age']), 'Age'] = df['Age'].mean()
pd.isnull(df['Age']).sum()

0

In [81]:
x_data = df.iloc[:,1:].values
y_data = df.iloc[:, 0].values.reshape(-1,1)
y_data

array([[0],
       [0],
       [1],
       ...,
       [0],
       [1],
       [0]])

In [82]:
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
x_data = min_max_scaler.fit_transform(x_data)

In [83]:
import numpy as np
from sklearn.model_selection import train_test_split 

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2)
x_train[:2]

array([[0.26666667, 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        ],
       [0.21333333, 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.     

In [84]:
y_test.reshape(-1,1).shape

(3917, 1)

In [93]:
from sklearn import linear_model, datasets

logreg = linear_model.LogisticRegression()
logreg.fit(x_train, y_train.ravel())

LogisticRegression()

In [94]:
logreg.predict(x_test[:5])

array([0, 0, 0, 0, 0])

In [98]:
# 0일 확률과 1일 확률 ( 높은 것이 선택됨 )
logreg.predict_proba(x_test[:5])

array([[0.92981663, 0.07018337],
       [0.6349201 , 0.3650799 ],
       [0.83523175, 0.16476825],
       [0.66675338, 0.33324662],
       [0.59214287, 0.40785713]])