In [1]:
import sklearn
import numpy as np

In [2]:
from sklearn.datasets import load_iris
datasets = load_iris()

In [3]:
type(datasets)

sklearn.utils._bunch.Bunch

In [4]:
datasets.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [5]:
datasets['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
datasets['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
x_data = datasets['data']
y_data = datasets['target']

In [9]:
y_data[:5]

array([0, 0, 0, 0, 0])

In [10]:
y_data = y_data.reshape(-1, 1)
y_data[:5]

array([[0],
       [0],
       [0],
       [0],
       [0]])

In [11]:
one_hot_y = np.zeros((150,3)) 

In [12]:
for idx, y in enumerate(y_data):
    one_hot_y[idx][y[0]] = 1

In [13]:
one_hot_y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [17]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler

In [16]:
enc = OneHotEncoder()
enc.fit(y_data)

y_data = enc.transform(y_data).toarray()

y_data[-1]

array([0., 0., 1.])

In [18]:
min_max_scaler = MinMaxScaler()
x_data_minmax = min_max_scaler.fit_transform(x_data)
x_data_minmax[:3]

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667]])

In [20]:
x_0 = np.ones(x_data_minmax.shape[0])
x_data_minmax = np.column_stack((x_0, x_data_minmax))

x_data_minmax[:3]

array([[1.        , 0.22222222, 0.625     , 0.06779661, 0.04166667],
       [1.        , 0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [1.        , 0.11111111, 0.5       , 0.05084746, 0.04166667]])

In [21]:
weights = np.random.uniform(size = (3,5)) # 3개의 class, 5개의 features가 있기 때문
weights

array([[0.85067253, 0.73622898, 0.83478941, 0.29742812, 0.06006663],
       [0.80209521, 0.07190617, 0.33594737, 0.05142228, 0.38851721],
       [0.25376319, 0.88412271, 0.61993694, 0.02804629, 0.30916067]])

In [22]:
def softmax(z):
    e = np.exp(z)
    p = e / np.sum(np.exp(z), axis = 1).reshape([-1, 1])
    return p

In [23]:
z = x_data_minmax.dot(weights.T)

In [30]:
z[:5]

array([[1.55868974, 1.04771594, 0.85247863],
       [1.34387367, 0.97373212, 0.67420717],
       [1.36749669, 0.99686138, 0.67627529],
       [1.3223453 , 0.98260931, 0.62683635],
       [1.57302183, 1.05971636, 0.85375037]])

In [28]:
x_data_minmax.shape

(150, 5)

In [29]:
weights.shape

(3, 5)

In [26]:
z.shape

(150, 3)

In [24]:
softmax(z)[:5] # 각각의 클래스에 대한 확률값

array([[0.47768686, 0.28656965, 0.23574349],
       [0.45402625, 0.31356713, 0.23240662],
       [0.45635855, 0.31502232, 0.22861912],
       [0.4523293 , 0.32203958, 0.22563113],
       [0.47947351, 0.28697158, 0.23355491]])

In [31]:
def cross_entropy_function(y, x, weights):
    z = x_data_minmax.dot(weights.T)
    result = - np.sum( # 전체 데이터셋의 합
                np.sum(
                    (y * np.log(softmax(z))), axis=1).reshape((-1,1)) # 정답의 확률값만 남음
                )
    return result

In [32]:
def minimize_grdient(y, x, initial_weights, iterations = 500000, alpha=0.001):
    cost_history= []
    theta_history = []
    m = y.shape[0]
    theta = np.copy(initial_weights)
    
    number_of_classes = theta.shape[0]
    number_of_weights = theta.shape[1]
    
    for _ in range(iterations):
        original_theta = np.copy(theta)
        for k in range(number_of_classes):        
            for j in range(number_of_weights):
                partial_x = x[:, j]
                partial_entropy = y - softmax(x.dot(original_theta.T))
                theta[k][j]  = original_theta[k][j] + (
                    alpha* partial_entropy[:,k].dot(partial_x.T) ) /150
        if (_ % 10000) == 0:
            print(cross_entropy_function(y,x,theta)/150)
            cost_history.append(cross_entropy_function(y,x,theta))
    return theta, cost_history

In [33]:
theta, cost_history = minimize_grdient(y_data, x_data_minmax,weights)

1.1143387366365514
0.7195539016618124
0.594911612569049
0.5264968512735455
0.4817825490752934
0.44927291790173446
0.42397728110171223
0.40337482270242847
0.38604362809509124
0.37111273936011996
0.3580139231243389
0.3463576430228303
0.3358660580643505
0.32633446172225195
0.31760790270769185
0.3095663815639048
0.30211512810378033
0.2951780136499671
0.288692965913653
0.28260870236614627
0.27688235478822176
0.27147771024585643
0.2663638872575555
0.2615143248593808
0.25690600035584327
0.2525188167026533
0.24833511742274192
0.24433929859261516
0.24051749555322896
0.2368573277475563
0.23334768921356622
0.22997857526149518
0.2267409380711421
0.22362656558583352
0.22062797931224765
0.21773834756979313
0.2149514114480258
0.2122614212819471
0.20966308188355573
0.2071515051035876
0.20472216856202055
0.2023708795959235
0.20009374364099705
0.19788713639793978
0.19574767924370587
0.1936722174361961
0.19165780073319552
0.18970166610568903
0.18780122227457885
0.18595403584034145


In [34]:
theta

array([[ 4.07463369, -1.74528207,  5.03058476, -5.10310622, -5.28355629],
       [ 3.07650376,  1.47425918, -1.42214303,  0.75122695, -1.31431806],
       [-5.24460653,  1.96328076, -1.81776801,  4.72877595,  7.35561887]])

In [37]:
rand_index= np.random.randint(0,150,30)
rand_index

array([ 16, 148,  87, 128,  78,  65,  86, 108, 119, 121,  18,  54, 140,
       110,   9, 106,  81,  80,  76, 109,  85, 132, 105,  88, 149,  86,
        23,  95, 144, 111])

In [38]:
y_pred = np.argmax(softmax(x_data_minmax[rand_index].dot(theta.T)),axis=1) 
y_pred

array([0, 2, 1, 2, 1, 1, 1, 2, 1, 2, 0, 1, 2, 2, 0, 1, 1, 1, 1, 2, 1, 2,
       2, 1, 2, 1, 0, 1, 2, 2])

In [39]:
y_true = np.argmax(y_data[rand_index],axis=1)
y_true

array([0, 2, 1, 2, 1, 1, 1, 2, 2, 2, 0, 1, 2, 2, 0, 2, 1, 1, 1, 2, 1, 2,
       2, 1, 2, 1, 0, 1, 2, 2])

In [40]:
sum(y_pred == y_true) / len(rand_index)

0.9333333333333333