### comparison operation (all, any, logical)

#### all, any

In [4]:
import numpy as np

In [5]:
a = np.arange(6).reshape(2,-1)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
np.all(a<3), np.any(a<3)

(False, True)

In [7]:
test_a = np.array([1,2,3])
test_b = np.array([4,5,6])

(test_a > test_b).any()

False

#### logical

![logical](../img/logical.png)

### np.where

In [8]:
c = np.array([1,3,0])
c

array([1, 3, 0])

In [9]:
# 조건을 만족하는 index값 반환
print(np.where(c < 3), '\n', c[np.where(c < 3)])

(array([0, 2]),) 
 [1 0]


In [10]:
# c가 3보다 작은 것이 True 일 때 3을 넣고 아니면 2를 넣는다
np.where(c < 3, 3, 2) 

array([3, 2, 3])

### isnan, isfinite

In [11]:
np.isnan(c), c[np.isnan(c)]

(array([False, False, False]), array([], dtype=int64))

### argmax, argmin

In [12]:
# 가장 큰 값과 작은 값의 INdex 반환
np.argmax(c), np.argmin(c)

(1, 2)

In [13]:
d = np.arange(10).reshape(2,-1)
d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
# 행에서 가장 큰 값의 index
print(np.argmax(d, axis=1),
# 열에서 가장 작은 값의 index
np.argmax(d, axis=0))

[4 4] [1 1 1 1 1]


### argsort

- 크기 순으로 정렬했을 때 index값 표시

In [15]:
e = np.array([1,3,2,4,6,7])
e

array([1, 3, 2, 4, 6, 7])

In [16]:
print( e,'\n',e[e.argsort()])

[1 3 2 4 6 7] 
 [1 2 3 4 6 7]


In [17]:
e.argsort()[::-1]

array([5, 4, 3, 1, 2, 0])

## fancy index

![fancy](../img/fancy_index.png)
![fancy2](../img/fancy2.png)

### loadtxt & savetxt

 ![data](../img/loadtxt_savetxt.png)