## numpy 특징
- `list`와 달리 0~256 사이의 숫자라도 static하게 메모리를 할당하는 것이 아니기때문에 `is` 비교를 하면 `False`가 나온다

### Array nbytes
- 8bits = 1bytes
  - ex) 데이터 개수가 6이고 dtype = np.float64 라면 nbytes 는 6*8

### reshape

![reshape](../img/reshape.png)

### flatten
- 다차원 array를 1차원으로 변환

![flatten](../img/flatten.png)

### indexing for numpy array

![index_slicing](../img/index_slicing.png)

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]], float)

In [3]:
a[:,2:]

array([[ 3.,  4.,  5.],
       [ 8.,  9., 10.]])

In [4]:
a[1,1:3]

array([7., 8.])

In [5]:
a[1:3]

array([[ 6.,  7.,  8.,  9., 10.]])

> 슬라이싱 안 하고 하나의 행만 지정하면 1차원 백터로 표현된다

In [6]:
a[:, -1] # 모든행의 마지막 column

array([ 5., 10.])

![step](../img/step_slice.png)

### ones, zeros, empty

![](../img/zeros.png)
![](../img/empty.png)

![something_like](../img/something_like.png)

### identity

In [7]:
np.identity(n=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

![eye](../img/eye.png)

### diag

![diag](../img/diag.png)

### random sampling

In [8]:
np.random.uniform(0,1,10) # 균등분포 0~1까지 10개  

array([0.05467097, 0.04476744, 0.05414706, 0.72378454, 0.81358621,
       0.46448957, 0.11862573, 0.90002958, 0.21979914, 0.67002466])

### axis, sum

![axis](../img/axis.png)

![axis2](../img/axis2.png)

### concatenate

![concat](../img/concatenate.png)

### new axis

In [11]:
b = np.array([1,2])
b.reshape(-1, 2)

array([[1, 2]])

In [13]:
b[np.newaxis, :]

array([[1, 2]])

### Operations b/t arrays

![1](../img/operations1.png)

### Dot product

![dt](../img/dot.png)

### transpose

![t](../img/transpose.png)