In [1]:
from tensorflow import keras
from keras import layers # 퍼셉트론으로 구성된 은닉층, 입력층 ,출력층을 만들어냄

import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf

print(tf.__version__)

2.10.0


## 퍼셉트론

In [3]:
X = np.random.rand(1,5) # 하나의 row로 생각하면 됨 - row = observation, column  = feature
X

array([[0.21305838, 0.9715129 , 0.53979939, 0.4920065 , 0.55704499]])

In [4]:
# 퍼셉트론의 생성
l = layers.Dense(1, input_shape=[5]) # (출력 차원, [input shape])
l

In [5]:
# 퍼셉트론 처리 예시
l(X)

Metal device set to: Apple M1 Pro

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB



2022-10-12 23:58:46.088377: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-10-12 23:58:46.092151: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.2240498]], dtype=float32)>

## 퍼셉트론 (출력층이 여러개)

In [6]:
l=layers.Dense(3,input_shape=[5])
l(X)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 0.31125784, -0.02844411,  0.8935557 ]], dtype=float32)>

## 퍼셉트론 (활성화 함수)

In [7]:
# l=layers.Dense(3,input_shape=[5],activation='sigmoid')
# l=layers.Dense(3,input_shape=[5],activation='tanh')
l=layers.Dense(3,input_shape=[5],activation='relu')
l(X)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.35188258, 0.54613614, 0.3734083 ]], dtype=float32)>

## 여러개의 관측치 처리

In [8]:
X_1 = np.random.rand(10,5)
X_1

array([[0.06970103, 0.34433322, 0.23333288, 0.76291188, 0.90819518],
       [0.25912108, 0.92070686, 0.13234644, 0.47645723, 0.70470642],
       [0.2945076 , 0.05910556, 0.62706799, 0.13483032, 0.58111404],
       [0.70132638, 0.73594987, 0.32293018, 0.93944147, 0.87139848],
       [0.26241992, 0.49190882, 0.61001026, 0.36415777, 0.11476944],
       [0.39382732, 0.61962908, 0.7547038 , 0.99398985, 0.38798962],
       [0.3139559 , 0.01403045, 0.64696166, 0.81985062, 0.69573082],
       [0.53197648, 0.34346835, 0.70945765, 0.34299098, 0.35895989],
       [0.02700376, 0.24007752, 0.59793442, 0.77023228, 0.13774323],
       [0.92903066, 0.37121274, 0.66152366, 0.73595301, 0.37974266]])

In [10]:
l(X_1)

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 2.7955467e-01, 7.8504736e-04],
       [4.4401430e-02, 2.1130796e-01, 2.3967648e-01],
       [0.0000000e+00, 1.6885585e-01, 3.0086786e-01],
       [4.2976052e-01, 5.1506633e-01, 6.8058395e-01],
       [4.2153186e-01, 3.4187016e-01, 6.7750078e-01],
       [4.5791604e-02, 0.0000000e+00, 1.2429957e-01],
       [1.5444297e-01, 5.0403142e-01, 7.4777633e-01],
       [5.4081982e-01, 7.2038032e-02, 3.5151866e-01],
       [0.0000000e+00, 4.6639845e-01, 1.0253946e+00]], dtype=float32)>

# Deep Neural Network 만들기

## keras.Sequential 사용해 모델 만들기

In [28]:
X_2 = np.random.rand(1,5)
X_2

array([[0.11978813, 0.06316998, 0.74565671, 0.85322367, 0.93889749]])

In [29]:
model = keras.Sequential([
    layers.Dense(3, input_shape = [5], activation='relu')
])

In [30]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_8 (Dense)             (None, 3)                 18        
                                                                 
Total params: 18
Trainable params: 18
Non-trainable params: 0
_________________________________________________________________


In [31]:
model(X_2)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.       , 0.5243944, 0.       ]], dtype=float32)>

## 모델 층 추가

In [32]:
X_3 = np.random.rand(1,10)
X_3

array([[0.87536149, 0.16513437, 0.73576498, 0.01794222, 0.34337483,
        0.57174197, 0.06425005, 0.1324621 , 0.80555047, 0.75145681]])

In [34]:
model = keras.Sequential([
    layers.Dense(5, input_shape=[10], activation='relu'),
    layers.Dense(3, activation='sigmoid'), # 두번째 층부터 input 개수 안 써줘도 됨
])
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_11 (Dense)            (None, 5)                 55        
                                                                 
 dense_12 (Dense)            (None, 3)                 18        
                                                                 
Total params: 73
Trainable params: 73
Non-trainable params: 0
_________________________________________________________________


In [35]:
model(X_3)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.3350554 , 0.18313038, 0.3675803 ]], dtype=float32)>

## 더 딥한 뉴럴네트워크

In [38]:
model = keras.Sequential([
    layers.Dense(5, input_shape=[10], activation='relu'),
    layers.Dense(10,  activation='relu'), 
    layers.Dense(10,  activation='relu'), 
    layers.Dense(1,  activation='sigmoid')
])
model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_17 (Dense)            (None, 5)                 55        
                                                                 
 dense_18 (Dense)            (None, 10)                60        
                                                                 
 dense_19 (Dense)            (None, 10)                110       
                                                                 
 dense_20 (Dense)            (None, 1)                 11        
                                                                 
Total params: 236
Trainable params: 236
Non-trainable params: 0
_________________________________________________________________


In [39]:
model(X_3)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.71170235]], dtype=float32)>

## faltten layer